[ERROR]: during executing magic script /openlane/scripts/magic/wrapper.tcl
[ERROR]: Log: designs/adder/runs/auto_pnr/logs/signoff/39-drc.log
[ERROR]: Last 10 lines:
2 Magic internal units = 1 Lambda
Input style sky130(): scaleFactor=2, multiplier=2
The following types are not handled by extraction and will be treated as non-electrical types:
    ubm 
Scaled tech values by 2 / 1 to match internal grid scaling
Loading sky130A Device Generator Menu ...
Using technology "sky130A", version 1.0.466-0-gbdc9412
Cannot open /openlane/designs/adder/runs/auto_pnr/results/signoff/adder.gds.gds, /openlane/designs/adder/runs/auto_pnr/results/signoff/adder.gds.strm or /openlane/designs/adder/runs/auto_pnr/results/signoff/adder.gds to read GDS-II stream input.
Error: couldn't open "/openlane/designs/adder/runs/auto_pnr/reports/signoff/drc.rpt": no such file or directory
child process exited abnormally

[ERROR]: Creating issue reproducible...
[ERROR]: Failed to package reproducible.
[ERROR]: Step 39 (drc) failed with error:
-code 1 -level 0 -errorstack {INNER {invokeStk1 throw_error} CALL {run_tcl_script -tool magic -no_consume /openlane/scripts/magic/wrapper.tcl -indexed_log /openlane/designs/adder/runs/auto_pnr/logs/signoff/39-drc.log} CALL {run_magic_script /openlane/scripts/magic/drc.tcl -indexed_log /openlane/designs/adder/runs/auto_pnr/logs/signoff/39-drc.log} CALL run_magic_drc CALL run_drc_step CALL {run_non_interactive_mode -design adder -tag auto_pnr -overwrite}} -errorcode NONE -errorinfo {
    while executing
"throw_error"
    (procedure "run_tcl_script" line 214)
    invoked from within
"run_tcl_script -tool magic -no_consume $::env(SCRIPTS_DIR)/magic/wrapper.tcl -indexed_log $arg_values(-indexed_log)"
    (procedure "run_magic_script" line 12)
    invoked from within
"run_magic_script $::env(SCRIPTS_DIR)/magic/drc.tcl -indexed_log $log"
    (procedure "run_magic_drc" line 11)
    invoked from within
"run_magic_drc"
    (procedure "run_drc_step" line 9)
    invoked from within
"run_drc_step"} -errorline 1
[ERROR]: Failed to create manufacturability and metric reports:
[ERROR]: Traceback (most recent call last):
  File "/openlane/scripts/generate_reports.py", line 184, in <module>
    cli()
  File "/nix/store/8ywrzlq8yyqrif2sfvbgg8vsxhj80ry7-python3-3.11.9-env/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/8ywrzlq8yyqrif2sfvbgg8vsxhj80ry7-python3-3.11.9-env/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/nix/store/8ywrzlq8yyqrif2sfvbgg8vsxhj80ry7-python3-3.11.9-env/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/8ywrzlq8yyqrif2sfvbgg8vsxhj80ry7-python3-3.11.9-env/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openlane/scripts/generate_reports.py", line 51, in cli
    report = Report(design, tag, design_name, params, run_path).get_report()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openlane/scripts/report/report.py", line 809, in get_report
    *self.extract_all_values(),
     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openlane/scripts/report/report.py", line 359, in extract_all_values
    power_report = Artifact(
                   ^^^^^^^^^
  File "/openlane/scripts/report/report.py", line 62, in __init__
    self.pathname = matches[0]
                    ~~~~~~~^^^
IndexError: list index out of range
[ERROR]: Flow failed.
[ERROR]: There are setup violations in the design at the Typical corner. Please refer to 'designs/adder/runs/auto_pnr/reports/signoff/30-sta-rcx_nom/multi_corner_sta.max.rpt'.
[ERROR]: Flow failed.
